### PR TITLE
Extend 'run_args' in topomachine to support lists, dicts

### PR DESCRIPTION
**Pull request by mzagozen**
topomachine already supports `run_args` for passing a raw string containing all the arguments to a container. With `run_args_structured` we can keep the structure in JSON and then pass the arguments as:
- a list,
- as key value pairs

to the container. Note how the values are passed verbatim - there are no assumptions about prefixing the key names with '--' or quoting the values.

### CODE REVIEW

**Comment by plajjan** [comment]
@mzagozen why accept a dict at all? Isn't a list the natural thing? What's the upside of a dict?

**Comment by mzagozen** [comment]
@plajjan Sorry, I forgot to explain *why* this is useful 🤦. It allows you to both provide the arguments to the container at runtime *and* also query the value in a template. The first iteration only supported dictionaries because reading entries from a dict (with something like *jq*) is more natural than picking out a list entry from a fixed position. Then I added list support too because why not?

**Comment by mzagozen** [comment]
Your comment made me reconsider just using the existing `run_args` field instead of adding a new one. JSON schema allows for this kind of definition:

```json
"run_args": {
  "oneOf": [
    { "type": "string" },
    { "type": "array" },
    { "type": "object" }
  ]
}
```

**Comment by plajjan** [comment]
> Your comment made me reconsider just using the existing `run_args` field instead of adding a new one. JSON schema allows for this kind of 🦆 definition:
> 
> ```json
> "run_args": {
>   "oneOf": [
>     { "type": "string" },
>     { "type": "array" },
>     { "type": "object" }
>   ]
> }
> ```

Hah, even more duck typing! ;)

I'm not sure the capabilities of JSON-schema lends credibility to anything ;)  statically typed languages typically frown upon this kind of construct and I sort of tend to agree that it usually leads to better code to avoid a variable flipping between different types.

That said, if we ever rewrite topomachine in a certain statically typed language, we have the opportunity to revisit this. In the meantime, I'm OK with this :)

**Comment by plajjan** [comment]
Feel free to merge when you feel ready :)

**Pull request merged**
