### PR TITLE
Add --trace argument to xcon-ng

### PR DESCRIPTION
**Pull request by mzagozen**
Print relayed datagram sizes and healthcheck state.

### CODE REVIEW

**Comment by plajjan** [comment]
@mzagozen how do you do that with python argparse?

**Comment by mzagozen** [comment]
> @mzagozen how do you do that with python argparse?

xcon.py uses `nargs='+'`, works with `nargs='*'` too: https://docs.python.org/3/library/argparse.html#nargs

```
parser = argparse.ArgumentParser()
parser.add_argument('--foo', nargs='*')
parser.add_argument('--bar', nargs='*')
parser.add_argument('baz', nargs='*')
parser.parse_args('a b --foo x y --bar 1 2'.split())
Namespace(bar=['1', '2'], baz=['a', 'b'], foo=['x', 'y'])
```

**Comment by plajjan** [comment]
Oh right, I did `nargs="+"` differently to avoid the ambiguity you get with positional arguments... well also because it's easier to parse this way. hmmmmm

**Comment by mzagozen** [comment]
In https://github.com/actonlang/acton/issues/1730 we decided to not introduce additional ambiguities in the argument parser, so this stays as is for now. I will make the backwards incompatible switch to argparse later.

**Pull request closed without merging**
