### PR TITLE
Basic smoke test for SSH management connectivity

### PR DESCRIPTION
**Pull request by mzagozen**
Just make sure at least _something_ is listening on the management interface. Not the full implementation as proposed in #53, but it's better than nothing 😄

I will update the `vrnetlab/ci-builder` image in docker hub too.

### CODE REVIEW

**Comment by mzagozen** [comment]
These tests do not work in GitHub Actions because the test job runs in a container provided by https://github.com/actions/runner-container-hooks. This container has access to the hosts `/var/run/docker.sock` so it can build images and start sibling test device containers. It is attached to an isolated job-specific network. named `github_network_<uuid>`. The sibling test containers are attached to the default *bridge* network so of course the two cannot communicate. I need to figure out how to grab the name of the job-specific network, push it into the test job container and attach the test device container to it.

**Comment by plajjan** [comment]
@mzagozen should the test be run in a "test" container that we start from the main job container? That way it'll get attached to the same network as the other containers!? It also means if we need / want more tooling, that can end up in the test container image rather than need to be installed in the main job container?!

**Comment by mzagozen** [comment]
Good suggestion, I actually had a draft version where I just ran `sshpass` in a container. To run the full test script I had to add the extra step of copying the test script to the container because we can't bind mount a path from within the sibling job script container.

It works and is future proof enough that we can extend the test suite in future. The failures we're seeing now are a result of actual _csr_ and _xrv9k_ build and/or startup failures.

**Comment by mzagozen** [comment]
Will investigate and address the specific platform version failures separately.

**Pull request merged**
